spring:
  profiles:
    active:
    - dev

spring:
  profiles: dev
  application:
    name: microservicescloud-config-dev


spring:
  profiles: test
  application:
    name: microservicescloud-config-test
  